DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS movements CASCADE;
DROP TABLE IF EXISTS user_workouts CASCADE;
DROP TABLE IF EXISTS intervals CASCADE;
DROP TABLE IF EXISTS workouts_completed CASCADE;