/**
 * this component renders are workout cards
 * PARENT COMPONENT : Workouts.jsx
 * 
 * PROPS :
 * ID => id from DB - primary key in Workouts Table
 * NAME => name give to workout from User
 * DESCRIPTION => description of workout given from User
 * DATE -> autogenerated when Workout added to DB // formats the date string into readable form first :)
 * 
 * RETURNS : an individual card for Workout stored in data Column in Workouts Table 
 */


export default function Card({id, name, description, date }) {
    const formattedDate = Intl.DateTimeFormat('en-US', {year: 'numeric', month: '2-digit',day: '2-digit'}).format(date)
    return ( 
        <a href={`/play/${id}`} className="block w-48 max-w-xl px-4 py-2 bg-grred rounded-lg shadow-md hover:bg-gray-100 dark:bg-grred dark:hover:bg-gray-700">
            <p className="text-sm text-grgrey dark:text-grgrey text-right">{id}</p>
            <div className=" text-xl tracking-tight text-gray-900 dark:text-white uppercase ">WORKOUT : {name}</div>
            <p className="text-sm text-grgrey dark:text-grgrey truncate">{description}</p>
            <p className="text-sm text-grwhite dark:text-grwhite text-right">{formattedDate}</p>
        </a>  
    )
}